name: practice-job
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -name: copying code to machine
       uses: actions/checkout@v4
      -name: install dependencies
       run: npm install ci
      -name: Lint
       run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -name: copying code to machine
       uses: actions/checkout@v4
      -name: install dependencies
       run: npm install ci
      -name: Test
       run: npm run test
  deploy:
    needs: [lint,test]
    runs-on: ubuntu-latest
    steps:
      -name: copying code to machine
       uses: actions/checkout@v4
      -name: install dependencies
       run: npm install ci
      -name: Deploy
       run: npm run build
      -name: deploying meesage
       run: echo "deploying...."


      
      