name: Practice-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: install code on ubuntu
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install ci
      - name: lint
        run: npm run lint
      - name: test code
        run: npm run test
      - name: deploy code
        run: npm run build
      - name: deploying code
        run: echo "deploying..."